POST  http://localhost:8000/user/register
Content-Type: application/json

{
    "email" : "subba2001@gmail.com",
    "password" : "subba",
    "roles" : ["admin","user"]
}

###

POST  http://localhost:8000/user/login
Content-Type: application/json

{
    "email" : "subba2001@gmail.com",
    "password" : "subba"
    
}

