POST  http://localhost:3000/user/register
Content-Type: application/json

{
    "email" : "laya2001@gmail.com",
    "password" : "laya",
    "roles" : ["admin","user"]
}

###

POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "email" : "jahnavipennabadi2001@gmail.com",
    "password" : "jan",
    "roles" : ["user","admin"]
    
}
